In [2]:
        import pandas as pd
        from pandas_profiling import ProfileReport
        from datetime import datetime as dt
        import os
        import sys
        import seaborn as sns
        import numpy as np
        import matplotlib.pyplot as plt
        %matplotlib inline

In [4]:
df = pd.read_csv('S:/Amazon Product Review/Data Set/7817_1.csv', low_memory=False)
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [5]:
profile = ProfileReport(df, title='Amazon Product review_1', explorative=True)

In [6]:
profile.to_file("output_1.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.describe()

,ean,reviews.numHelpful,reviews.rating,reviews.userCity,reviews.userProvince,sizes,upc
count,8.980000e+02,900.000000,1177.000000,0.0,0.0,0.0,8.980000e+02
mean,8.443135e+11,83.584444,4.359388,NaN,NaN,NaN,8.443135e+11
std,3.416444e+09,197.150238,1.021445,NaN,NaN,NaN,3.416444e+09
min,8.416670e+11,0.000000,1.000000,NaN,NaN,NaN,8.416670e+11
25%,8.416670e+11,0.000000,4.000000,NaN,NaN,NaN,8.416670e+11
50%,8.416670e+11,0.000000,5.000000,NaN,NaN,NaN,8.416670e+11
75%,8.487190e+11,34.000000,5.000000,NaN,NaN,NaN,8.487190e+11
max,8.487190e+11,997.000000,5.000000,NaN,NaN,NaN,8.487190e+11

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1597 non-null   object
 1   asins                 1597 non-null   object
 2   brand                 1597 non-null   object
 3   categories            1597 non-null   object
 4   colors                774 non-null    object
 5   dateAdded             1597 non-null   object
 6   dateUpdated           1597 non-null   object
 7   dimension             565 non-null    object
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   object
 10  manufacturer          965 non-null    object
 11  manufacturerNumber    902 non-null    object
 12  name                  1597 non-null   object
 13  prices                1597 non-null   object
 14  reviews.date          1217 non-null   object
 15  reviews.doRecommend   539 non-null    object
 16  reviews.numHelpful    900 non-null    float64
 17  reviews.rating        1177 non-null   float64
 18  reviews.sourceURLs    1597 non-null   object
 19  reviews.text          1597 non-null   object
 20  reviews.title         1580 non-null   object
 21  reviews.userCity      0 non-null      float64
 22  reviews.userProvince  0 non-null      float64
 23  reviews.username      1580 non-null   object
 24  sizes                 0 non-null      float64
 25  upc                   898 non-null    float64
 26  weight                686 non-null    object
dtypes: float64(7), object(20)
memory usage: 337.0+ KB

In [9]:
df['dateAdded'] = pd.to_datetime(df['dateAdded'])
print(df.to_string())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [10]:
df['dateAdded']

0      2016-03-08 20:21:53+00:00
1      2016-03-08 20:21:53+00:00
2      2016-03-08 20:21:53+00:00
3      2016-03-08 20:21:53+00:00
4      2016-03-08 20:21:53+00:00
                  ...
1592   2016-04-02 14:40:43+00:00
1593   2016-04-02 14:40:43+00:00
1594   2016-04-02 14:40:43+00:00
1595   2016-04-02 14:40:43+00:00
1596   2016-04-02 14:40:43+00:00
Name: dateAdded, Length: 1597, dtype: datetime64[ns, UTC]

In [12]:
df.rename({"id":"ID", "dateAdded":"DATE", "asins":"PRODUCT ID","brand":"BRAND", "categories":"CATAGORY",
                    "reviews.rating":"RATING", "reviews.sourceURLs":"SOURCE", "reviews.text":"REVIEWS", "reviews.title":"REVIEWS TITLE"}, axis = 1, inplace = True)

In [16]:
df.drop(['colors','dateUpdated','ean','keys','manufacturer','manufacturerNumber','name','prices','reviews.date','reviews.doRecommend','reviews.numHelpful', 'reviews.username', 'sizes', 'upc','weight'], axis = 1, inplace=True)

In [19]:
df.drop(['dimension','reviews.userCity','reviews.userProvince'], axis=1, inplace = True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             1597 non-null   object
 1   PRODUCT ID     1597 non-null   object
 2   BRAND          1597 non-null   object
 3   CATAGORY       1597 non-null   object
 4   DATE           1597 non-null   datetime64[ns, UTC]
 5   RATING         1177 non-null   float64
 6   SOURCE         1597 non-null   object
 7   REVIEWS        1597 non-null   object
 8   REVIEWS TITLE  1580 non-null   object
dtypes: datetime64[ns, UTC](1), float64(1), object(7)
memory usage: 112.4+ KB

In [23]:
df.to_csv('Amazon_Dataset_1', index=False)

In [24]:
df1 = pd.read_csv('Amazon_dataset.csv')

In [25]:
df1.head()

,ID,DATE,dateUpdated,PRODUCT ID,BRAND,CATAGORY,PRIMARY CATAGORY,RATING,SOURCE,REVIEWS,REVIEWS TITLE
0,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,2018-10-25T16:36:31Z,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,3,http://reviews.bestbuy.com/3545/5442403/review...,I thought it would be as big as small paper bu...,Too small
1,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,2018-10-25T16:36:31Z,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,http://reviews.bestbuy.com/3545/5442403/review...,This kindle is light and easy to use especiall...,Great light reader. Easy to use at the beach
2,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,2018-10-25T16:36:31Z,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,4,https://reviews.bestbuy.com/3545/5442403/revie...,Didnt know how much i'd use a kindle so went f...,Great for the price
3,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,2018-10-25T16:36:31Z,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,https://redsky.target.com/groot-domain-api/v1/...,I am 100 happy with my purchase. I caught it o...,A Great Buy
4,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,2018-10-25T16:36:31Z,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,https://reviews.bestbuy.com/3545/5442403/revie...,Solid entry level Kindle. Great for kids. Gift...,Solid entry-level Kindle. Great for kids

In [26]:
df1.drop(['dateUpdated'], axis = 1, inplace = True)

In [27]:
df1.head()

,ID,DATE,PRODUCT ID,BRAND,CATAGORY,PRIMARY CATAGORY,RATING,SOURCE,REVIEWS,REVIEWS TITLE
0,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,3,http://reviews.bestbuy.com/3545/5442403/review...,I thought it would be as big as small paper bu...,Too small
1,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,http://reviews.bestbuy.com/3545/5442403/review...,This kindle is light and easy to use especiall...,Great light reader. Easy to use at the beach
2,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,4,https://reviews.bestbuy.com/3545/5442403/revie...,Didnt know how much i'd use a kindle so went f...,Great for the price
3,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,https://redsky.target.com/groot-domain-api/v1/...,I am 100 happy with my purchase. I caught it o...,A Great Buy
4,AVqVGZNvQMlgsOJE6eUY,2017-03-03 16:56:05+00:00,B00ZV9PXP2,Amazon,"Computers,Electronics Features,Tablets,Electro...",Electronics,5,https://reviews.bestbuy.com/3545/5442403/revie...,Solid entry level Kindle. Great for kids. Gift...,Solid entry-level Kindle. Great for kids

In [29]:
Complete_dataset =  [df, df1]

In [30]:
result = pd.concat(Complete_dataset)

In [38]:
result['DATE'] = pd.to_datetime(result['DATE'], utc=True)
print(result.to_string())

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [41]:
result

,ID,PRODUCT ID,BRAND,CATAGORY,DATE,RATING,SOURCE,REVIEWS,REVIEWS TITLE,PRIMARY CATAGORY
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08 20:21:53+00:00,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08 20:21:53+00:00,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08 20:21:53+00:00,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08 20:21:53+00:00,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08 20:21:53+00:00,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN
...,...,...,...,...,...,...,...,...,...,...
33327,AVqkIhxunnc1JgDc3kg_,B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...",2017-03-06 14:59:43+00:00,5.0,http://reviews.bestbuy.com/3545/5620410/review...,I got 2 of these for my 8 yr old twins. My 11 ...,Xmas gift,Electronics
33328,AVqkIhxunnc1JgDc3kg_,B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...",2017-03-06 14:59:43+00:00,4.0,http://reviews.bestbuy.com/3545/5620410/review...,I bought this for my niece for a Christmas gif...,yes it is a great tablet.,Electronics
33329,AVqkIhxunnc1JgDc3kg_,B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...",2017-03-06 14:59:43+00:00,5.0,http://reviews.bestbuy.com/3545/5620410/review...,"Very nice for light internet browsing, keeping...",You get a lot for the price!,Electronics
33330,AVqkIhxunnc1JgDc3kg_,B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...",2017-03-06 14:59:43+00:00,5.0,http://reviews.bestbuy.com/3545/5620410/review...,This Tablet does absolutely everything I want!...,You get the entire World for less than $100!,Electronics
33331,AVqkIhxunnc1JgDc3kg_,B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...",2017-03-06 14:59:43+00:00,4.0,http://reviews.bestbuy.com/3545/5620410/review...,"At ninety dollars, the expectionations are low...",You get what your paying for,Electronics

In [42]:
result.to_csv('Dataset_Amazon', index = False)